name: Automatically trigger

on:
  workflow_dispatch:

env:
  AZ_ML_WORKSPACE_NAME: sergioml_mlworkspace
  RG_NAME: sergioml
  COMPUTE_INSTANCE_SIZE: STANDARD_DS11_V2

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: DEV ENVIRONMENT
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create Compute instance
      run: |
        az ml compute create -g $RG_NAME --workspace-name $AZ_ML_WORKSPACE_NAME --name automated --size $COMPUTE_INSTANCE_SIZE --type ComputeInstance
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create -g $RG_NAME --workspace-name $AZ_ML_WORKSPACE_NAME --file src/job.yml

  production:
    runs-on: ubuntu-latest
    needs: experiment
    environment: PROD ENVIRONMENT
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create Compute instance
      run: |
        az ml compute create -g $RG_NAME --workspace-name $AZ_ML_WORKSPACE_NAME --name automated --size $COMPUTE_INSTANCE_SIZE --type ComputeInstance
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create -g $RG_NAME --workspace-name $AZ_ML_WORKSPACE_NAME --file src/job.yml --set inputs.diabetes.path="azureml:diabetes-prod-folder:2"

